config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { :registrations => "registrations" }

  unauthenticated :user do
    root to: "pages#home", as: :unauthorized_root_path
  end

  authenticated :user do
    root to: 'dashboard#index'
  end

  get 'review', to: 'dashboard#review', as: 'review'

  resources :entries do
    get 'promote', on: :member, to: 'entries#promote'
    get 'cover_sheet', on: :member, to: 'entries#cover_sheet'
    resources :user_entries, only: [:new, :create, :index, :destroy]
    resources :scoresheets, only: [:new, :create, :show, :update, :edit, :destroy]
  end

  scope "/admin" do
    resources :users, except: :new do
      resources :judge_preferences, only: [:new, :create, :index]
    end
    resources :user_roles
    resources :divisions do
      get 'scoresheet', on: :member
    end
    resources :regions
    resources :fairs do
      get 'view_schedule', on: :member, to: 'fairs#view_schedule'
      post 'schedule', on: :member, to: 'fairs#submit_schedule'
      get 'schedule', on: :member
      get 'review', on: :member
      get 'tallyroom', on: :member, to: 'fairs#tallyroom'
      resources :judge_assigns
    end
    resources :timeslots
    resources :criteria
    resources :criteria_types
    resources :criteria_descriptions
    resources :applicable_criteria
    resources :scoresheets, only: [:index]
    resources :scores
    resources :judge_fairs, except: [:show]
    resources :locations
    resources :peerages
  end
end

app/controllers/dashboard_controller.rb
include FairsHelper

class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :assign_next_fair

  def index
  end

  def review
    @user = current_user
    @entries = Entry.fair_entries(@next_fair.id).user_entries(current_user).joins(:timeslot).order("timeslots.order")
    @judging = Entry.fair_entries(@next_fair.id).judge_assigned_entries(current_user).joins(:timeslot).order("timeslots.order")
    @everything = (@entries + @judging).sort { |a, b| a.timeslot.order <=> b.timeslot.order }
  end

  private
  def assign_next_fair
    @next_fair = next_fair
  end
end

app/views/dashboard/index.html.erb
<% if current_user.admin? %>
  <h3>Tallyroom</h3>
  <%= link_to 'Tallyroom', tallyroom_fair_path(@next_fair) %>
  <h3>Admin Management</h3>
  <%= link_to 'Scoresheet Management', scoresheets_path %>
  <br>
  <h3>User Management</h3>
  <%= link_to 'User Management', users_path %>
  <br>
  <%= link_to 'User Role Management', user_roles_path %>
  <br>
  <%= link_to 'User Preferences', current_user %>
  <br>
  <%= link_to 'Manage your judging preferences', user_judge_preferences_path(current_user) %>
  <br>
  <%= link_to 'Volunteer for a Fair', judge_fairs_path %>
  <% if !@next_fair.nil? && @next_fair.scheduling_visible %>
    <br>
    <%= link_to 'Review your Schedule', review_path %>
  <% end %>
  <% if !@next_fair.nil? && scoresheets_visible?(@next_fair, current_user)  %>
    <br>
    <%= link_to 'Submit a Scoresheet', scoresheets_path %>
  <% end %>
  <h3>System Management</h3>
  <%= link_to 'Division Management', divisions_path %>
  <br>
  <%= link_to 'Region Management', regions_path %>
  <br>
  <%= link_to 'Timeslot Management', timeslots_path %>
  <br>
  <%= link_to 'Criteria Type Management', criteria_types_path %>
  <br>
  <%= link_to 'Criteria Management', criteria_path %>
  <br>
  <%= link_to 'Category Management', categories_path %>
  <br>
  <%= link_to 'Peerage Title Management', peerages_path %>
  <h3>Fair Management</h3>
  <%= link_to 'Fair Management', fairs_path %>
  <br>
  <%= link_to 'Room Location Management', locations_url %>
  <br>
  <%= link_to 'Entry Management', entries_path %>
<% else %>
  <%= link_to 'Manage Your Entries', entries_path %>
  <br>
  <%= link_to 'Volunteer for a Fair', judge_fairs_path %>
  <br>
  <%= link_to 'User Preferences', current_user %>
  <br>
  <%= link_to 'Manage your judging preferences', user_judge_preferences_path(current_user) %>
  <% if !@next_fair.nil? && @next_fair.scheduling_visible %>
    <br>
    <%= link_to 'Review your Schedule', review_path %>
  <% end %>
  <% if !@next_fair.nil? && scoresheets_visible?(@next_fair, current_user)  %>
    <br>
    <%= link_to 'Submit a Scoresheet', scoresheets_path %>
  <% end %>
<% end %>

app/views/dashboard/review.html.erb
<h2>Your Final Schedule</h2>

<table>
  <thead>
  <tr>
    <th>Entry Name</th>
    <th>Timeslot</th>
    <th>Room</th>
  </tr>
  </thead>

  <tbody>
  <% @everything.each do |entry| %>
    <tr>
      <td><%= entry.entry_name %></td>
      <td><%= entry.timeslot.description %></td>
      <td><%= entry.location.description %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>

<h2>Your Judging Assignments</h2>

<table>
  <thead>
  <tr>
    <th>Entry Name</th>
    <th>Timeslot</th>
    <th>Room</th>
  </tr>
  </thead>

  <tbody>
  <% @judging.each do |entry| %>
    <tr>
      <td><%= entry.entry_name %></td>
      <td><%= entry.timeslot.description %></td>
      <td><%= entry.location.description %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>

<h2>Your Entries</h2>

<table>
  <thead>
  <tr>
    <th>Entry Name</th>
    <th>Timeslot</th>
    <th>Room</th>
  </tr>
  </thead>

  <tbody>
  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.entry_name %></td>
      <td><%= entry.timeslot.description %></td>
      <td><%= entry.location.description %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<br><%= link_to 'Back', root_path %>