config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { :registrations => "registrations" }

  unauthenticated :user do
    root to: "pages#home", as: :unauthorized_root_path
  end

  authenticated :user do
    root to: 'dashboard#index'
  end

  get 'review', to: 'dashboard#review', as: 'review'

  resources :entries do
    get 'promote', on: :member, to: 'entries#promote'
    get 'cover_sheet', on: :member, to: 'entries#cover_sheet'
    resources :user_entries, only: [:new, :create, :index, :destroy]
    resources :scoresheets, only: [:new, :create, :show, :update, :edit, :destroy]
  end

  scope "/admin" do
    resources :users, except: :new do
      resources :judge_preferences, only: [:new, :create, :index]
    end
    resources :user_roles
    resources :divisions do
      get 'scoresheet', on: :member
    end
    resources :regions
    resources :fairs do
      get 'view_schedule', on: :member, to: 'fairs#view_schedule'
      post 'schedule', on: :member, to: 'fairs#submit_schedule'
      get 'schedule', on: :member
      get 'review', on: :member
      get 'tallyroom', on: :member, to: 'fairs#tallyroom'
      resources :judge_assigns
    end
    resources :timeslots
    resources :criteria
    resources :criteria_types
    resources :criteria_descriptions
    resources :applicable_criteria
    resources :scoresheets, only: [:index]
    resources :scores
    resources :judge_fairs, except: [:show]
    resources :locations
    resources :peerages
  end
end

app/models/judge_preference.rb
class JudgePreference < ApplicationRecord
  belongs_to :user
  belongs_to :category

  scope :for_user, -> (user) {where("user_id = ?", user.id)}
  scope :default_order, -> {joins(:category).order(:name)}
end

app/controllers/judge_preferences_controller.rb
class JudgePreferencesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_judge_preference, only: [:show, :edit]
  before_action :set_user
  before_action :verify_user_preference

  def verify_user_preference
    authorize params[:user_id], :owns_preference?, policy_class: JudgePreferencePolicy
  end

  # GET /judge_preferences
  # GET /judge_preferences.json
  def index
    if current_user.admin?
      @user = User.find(params[:user_id])
      @judge_preferences = JudgePreference.for_user(User.find(params[:user_id])).default_order
    else
      @judge_preferences = JudgePreference.for_user(current_user).default_order
    end
  end

  # GET /judge_preferences/1
  # GET /judge_preferences/1.json
  # def show
  # end

  # GET /judge_preferences/new
  def new
    @user = User.find(params[:user_id]) if current_user.admin?
    @judge_preference = JudgePreference.new
  end

  # GET /judge_preferences/1/edit
  # def edit
  # end

  # POST /judge_preferences
  # POST /judge_preferences.json
  def create
    user = current_user.admin? ? User.find(params[:user_id]) : @user
    selected_categories = params[:user][:selected_categories].drop(1)
    #destroy all unselected divisions
    user.selected_categories.each do |category_id|
      JudgePreference.find_by(user_id: user.id, category_id: category_id).destroy unless selected_categories.include?(category_id.to_s)
    end

    selected_categories.each do |category_id|
      JudgePreference.find_or_create_by({user_id: user.id, category_id: category_id})
    end

    respond_to do |format|
      format.html { redirect_to user_judge_preferences_url, notice: 'Judge preference was successfully created.' }
      format.json { render :show, status: :created, location: @judge_preference }
    end
  end

  # PATCH/PUT /judge_preferences/1
  # PATCH/PUT /judge_preferences/1.json
  # def update
  #   respond_to do |format|
  #     if @judge_preference.update(judge_preference_params)
  #       format.html { redirect_to @judge_preference, notice: 'Judge preference was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @judge_preference }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @judge_preference.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /judge_preferences/1
  # DELETE /judge_preferences/1.json
  # def destroy
  #   @judge_preferences = JudgePreference.all
  #   @judge_preference.destroy
  #   respond_to do |format|
  #     format.html { redirect_to user_judge_preferences_url, notice: 'Judge preference was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_judge_preference
      @judge_preference = JudgePreference.find(params[:id])
    end

  def set_user
    @user = current_user
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def judge_preference_params
      params.require(:judge_preference).require(:judge_preferences).permit(:category_id).merge({user_id: @current_user.id})
    end
end

app/helpers/judge_preferences_helper.rb
module JudgePreferencesHelper
end

app/views/judge_preferences/_form.html.erb
<%= form_with(model: [@user, judge_preference], local: true) do |form| %>
  <% if judge_preference.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(judge_preference.errors.count, "error") %> prohibited this judge_preference from being saved:</h2>

      <ul>
        <% judge_preference.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin? && @user.id != current_user.id %>
    <div class="alert alert-danger">
      <h4>You are currently in admin mode and are viewing a user other than yourself.</h4>
    </div>
  <% end %>

  <div class="field">
    <%= collection_check_boxes(:user, :selected_categories, Category.all.default_order, :id, :name) do |b| %>
      <br>
      <%= b.label(class: "checkbox-inline", :"data-value" => b.value) { b.check_box + b.text } %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Update Preferences" %>
  </div>
<% end %>

app/views/judge_preferences/edit.html.erb
<h1>Editing Judge Preference</h1>

<%= render 'form', judge_preference: @judge_preference %>

<%= link_to 'Show', @judge_preference %> |
<%= link_to 'Back', user_judge_preferences_path(@user) %>

app/views/judge_preferences/index.html.erb
<% if current_user.admin? && @user.id != current_user.id %>
  <div class="alert alert-danger">
    <h4>You are currently in admin mode and are viewing a user other than yourself.</h4>
  </div>
<% end %>

<h1>Your preferences as a judge</h1>

<table>
  <thead>
    <tr>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @judge_preferences.each do |judge_preference| %>
      <tr>
        <td><%= judge_preference.category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit preferences', new_user_judge_preference_path(@user) %>
<br><%= link_to 'Back', root_path %>

app/views/judge_preferences/new.html.erb
<h1>Edit Judge Preferences</h1>

<%= render 'form', judge_preference: @judge_preference %>

<%= link_to 'Back', user_judge_preferences_path(@user) %>

app/views/judge_preferences/show.html.erb
<%= link_to 'Edit', edit_judge_preference_path(@judge_preference) %> |
<%= link_to 'Back', judge_preferences_path %>