config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { :registrations => "registrations" }

  unauthenticated :user do
    root to: "pages#home", as: :unauthorized_root_path
  end

  authenticated :user do
    root to: 'dashboard#index'
  end

  get 'review', to: 'dashboard#review', as: 'review'

  resources :entries do
    get 'promote', on: :member, to: 'entries#promote'
    get 'cover_sheet', on: :member, to: 'entries#cover_sheet'
    resources :user_entries, only: [:new, :create, :index, :destroy]
    resources :scoresheets, only: [:new, :create, :show, :update, :edit, :destroy]
  end

  scope "/admin" do
    resources :users, except: :new do
      resources :judge_preferences, only: [:new, :create, :index]
    end
    resources :user_roles
    resources :divisions do
      get 'scoresheet', on: :member
    end
    resources :regions
    resources :fairs do
      get 'view_schedule', on: :member, to: 'fairs#view_schedule'
      post 'schedule', on: :member, to: 'fairs#submit_schedule'
      get 'schedule', on: :member
      get 'review', on: :member
      get 'tallyroom', on: :member, to: 'fairs#tallyroom'
      resources :judge_assigns
    end
    resources :timeslots
    resources :criteria
    resources :criteria_types
    resources :criteria_descriptions
    resources :applicable_criteria
    resources :scoresheets, only: [:index]
    resources :scores
    resources :judge_fairs, except: [:show]
    resources :locations
    resources :peerages
  end
end

app/models/user_entry.rb
class UserEntry < ApplicationRecord
  belongs_to :user
  belongs_to :entry

  def self.entrants(entry)
    user_entries = UserEntry.where(entry_id: entry.id).pluck(:user_id)
    User.find(user_entries)
  end
end

app/controllers/user_entries_controller.rb
class UserEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_entry, only: [:show, :edit, :destroy]
  before_action :set_entry
  before_action :verify_user_entry

  def verify_user_entry
    authorize @entry, :owns_entry?
  end

  # GET /user_entries
  # GET /user_entries.json
  def index
    @user_entries = UserEntry.where(entry_id: @entry.id).reject{|record| record.user_id == current_user.id}
  end

  # GET /user_entries/1
  # GET /user_entries/1.json
  # def show
  # end

  # GET /user_entries/new
  def new
    @user_entry = UserEntry.new
  end

  # GET /user_entries/1/edit
  # def edit
  # end

  # POST /user_entries
  # POST /user_entries.json
  def create
    @user_entry = UserEntry.new(user_entry_params)

    respond_to do |format|
      if @user_entry.save
        format.html { redirect_to entry_user_entries_url, notice: 'Judge preference was successfully created.' }
        format.json { render :show, status: :created, location: @user_entry }
      else
        format.html { render :new }
        format.json { render json: @user_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_entries/1
  # PATCH/PUT /user_entries/1.json
  # def update
  #   respond_to do |format|
  #     if @user_entry.update(user_entry_params)
  #       format.html { redirect_to @user_entry, notice: 'Judge preference was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user_entry }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user_entry.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /user_entries/1
  # DELETE /user_entries/1.json
  def destroy
    @user_entries = UserEntry.all
    @user_entry.destroy
    respond_to do |format|
      format.html { redirect_to entry_user_entries_url, notice: 'Judge preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_entry
      @user_entry = UserEntry.find(params[:id])
    end

  def set_entry
    @entry = Entry.find(params[:entry_id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_entry_params
      params.require(:user_entry).require(:user_entries).permit(:user_id).merge({entry_id: @entry.id})
    end
end

app/views/user_entries/_form.html.erb
<%= form_with(model: [@entry, user_entry], local: true) do |form| %>
  <% if user_entry.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(user_entry.errors.count, "error") %> prohibited this user_entry from being saved:</h2>

      <ul>
        <% user_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :user_entries do |j| %>
    <div class="field">
      <%= j.label :user %>
      <%= j.select :user_id, User.all.reject{|record| record.id == current_user.id}.map{ |m| ["#{m.email} - #{m.sca_name}", m.id] }%>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_entries/edit.html.erb
<h1>Editing Entrants</h1>

<%= render 'form', user_entry: @user_entry %>

<%= link_to 'Show', @user_entry %> |
<%= link_to 'Back', entry_user_entries_path(@user) %>

app/views/user_entries/index.html.erb
<h1>Group Entry Participants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_entries.each do |user_entry| %>
      <tr>
        <td><%= user_entry.user.email %></td>
        <td><%= link_to 'Remove Entrant', [@entry, user_entry], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a new entrant', new_entry_user_entry_path(@entry) %>
<br><%= link_to 'Back', entries_path %>

app/views/user_entries/new.html.erb
<h1>New Entrant</h1>

<%= render 'form', user_entry: @user_entry %>

<%= link_to 'Back', entry_user_entries_path(@entry) %>

app/views/user_entries/show.html.erb
<%= link_to 'Edit', edit_user_entry_path(@judge_preference) %> |
<%= link_to 'Back', user_entries_path %>