config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { :registrations => "registrations" }

  unauthenticated :user do
    root to: "pages#home", as: :unauthorized_root_path
  end

  authenticated :user do
    root to: 'dashboard#index'
  end

  get 'review', to: 'dashboard#review', as: 'review'

  resources :entries do
    get 'promote', on: :member, to: 'entries#promote'
    get 'cover_sheet', on: :member, to: 'entries#cover_sheet'
    resources :user_entries, only: [:new, :create, :index, :destroy]
    resources :scoresheets, only: [:new, :create, :show, :update, :edit, :destroy]
  end

  scope "/admin" do
    resources :users, except: :new do
      resources :judge_preferences, only: [:new, :create, :index]
    end
    resources :user_roles
    resources :divisions do
      get 'scoresheet', on: :member
    end
    resources :regions
    resources :fairs do
      get 'view_schedule', on: :member, to: 'fairs#view_schedule'
      post 'schedule', on: :member, to: 'fairs#submit_schedule'
      get 'schedule', on: :member
      get 'review', on: :member
      get 'tallyroom', on: :member, to: 'fairs#tallyroom'
      resources :judge_assigns
    end
    resources :timeslots
    resources :criteria
    resources :criteria_types
    resources :criteria_descriptions
    resources :applicable_criteria
    resources :scoresheets, only: [:index]
    resources :scores
    resources :judge_fairs, except: [:show]
    resources :locations
    resources :peerages
  end
end

app/models/scoresheet.rb
class Scoresheet < ApplicationRecord
  belongs_to :user
  belongs_to :entry
  has_many :scores, dependent: :destroy
  
  accepts_nested_attributes_for :scores

  scope :for_user, -> (user) { where("user_id = ?", user.id)}
  scope :for_fair, -> (fair) { joins(:entry).where(entries: {fair_id: fair.id})}

  def shadow_scoresheet?
    JudgeAssign.find_by(entry_id: entry_id, user_id: user_id).shadow
  end

  def total_score
    all_relevant_scores = self.scores.pluck(:score)
    all_relevant_scores.reduce(:+)
  end
end

app/controllers/scoresheets_controller.rb
include FairsHelper

class ScoresheetsController < ApplicationController
  before_action :set_scoresheet, only: [:show, :edit, :update, :destroy]
  before_action :set_entry, only: [:create, :new, :edit, :update, :show]
  before_action :verify_owns_scoresheet, only: [:show, :edit, :update, :destroy]  #TODO: re-enable this so it doesn't break things

  def verify_owns_scoresheet
    authorize @scoresheet, :owns_scoresheet?
  end

  # GET /scoresheets
  # GET /scoresheets.json
  def index
    fair = next_fair

    if fair.mail_in_scoresheets_allowed && !fair.scoresheets_allowed
      @entries = filter_unjudged(Entry.fair_entries(fair).judge_assigned_entries(current_user).joins(:division).where('divisions.name = ?', 'Research'))
    else
      @entries = filter_unjudged(Entry.fair_entries(fair).judge_assigned_entries(current_user))
    end

    if current_user.admin?
      @scoresheets = Scoresheet.all
    else
      @scoresheets = Scoresheet.for_user(current_user)
    end

    search_param = params[:fair]
    unless search_param.nil?
      @scoresheets = @scoresheets.joins(:entry).where(entry: {fair_id: search_param})
    end
  end


  # GET /scoresheets/1
  # GET /scoresheets/1.json
  def show
    @criteria_types = CriteriaTypeRepository.active_criteria
  end

  # GET /scoresheets/new
  def new
    @scoresheet = Scoresheet.new
    @criteria_types = CriteriaTypeRepository.active_criteria

    CriteriaTypeRepository.active_criteria.where(division_id: @entry.division.id).each do |criteria_type|
      @scoresheet.scores.build({criteria_type_id: criteria_type.id})
    end
  end

  # GET /scoresheets/1/edit
  def edit
  end

  # POST /scoresheets
  # POST /scoresheets.json
  def create
    @scoresheet = Scoresheet.new(scoresheet_params)
    @criteria_types = CriteriaTypeRepository.active_criteria

    CriteriaTypeRepository.active_criteria.where(division_id: @entry.division.id).each do |criteria_type|
      @scoresheet.scores.build({criteria_type_id: criteria_type.id})
    end

    update_scores

    respond_to do |format|
      if @scoresheet.save
        format.html { redirect_to [@scoresheet.entry, @scoresheet], notice: 'Scoresheet was successfully created.' }
        format.json { render :show, status: :created, location: @scoresheet }
      else
        format.html { render :new }
        format.json { render json: [@scoresheet.entry, @scoresheet.error], status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scoresheets/1
  # PATCH/PUT /scoresheets/1.json
  def update
    cheater_params = params.permit!
    Score.update(cheater_params[:scoresheet][:scores].keys, cheater_params[:scoresheet][:scores].values)

    @criteria_types = CriteriaTypeRepository.active_criteria

    respond_to do |format|
      if @scoresheet.update(scoresheet_params)
        format.html { redirect_to [@scoresheet.entry, @scoresheet], notice: 'Scoresheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @scoresheet }
      else
        format.html { render :edit }
        format.json { render json: [@scoresheet.entry, @scoresheet].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scoresheets/1
  # DELETE /scoresheets/1.json
  def destroy
    @scoresheet.destroy
    respond_to do |format|
      format.html { redirect_to scoresheets_url, notice: 'Scoresheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scoresheet
      @scoresheet = Scoresheet.find(params[:id])
    end

  def set_entry
    @entry = Entry.find(params[:entry_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def scoresheet_params
    if current_user.admin?
      params.permit(:entry_id).merge(user_id: params[:scoresheet][:user_id])
    else
      params.permit(:entry_id).merge(user_id: current_user.id)
    end
  end

  def score_params(params)
    params.permit(:criteria_type, :score, :comment)
  end

  def update_scores
    scores = params[:scoresheet][:scores]
    scores.each do |score|
      score_record = @scoresheet.scores.select{|n| n.criteria_type_id == score[:criteria_type_id].to_i}.first
      score_record.update(score_params(score))
      score_record.save
    end
  end

  def filter_unjudged(entries)
    entries.reject do |entry|
      !Scoresheet.find_by(entry_id: entry.id, user_id: current_user.id).nil?
    end
  end

  def filter_admin_unjudged(entries)
    entries.reject do |entry|
      JudgeAssign.where(entry_id: entry.id).count == Scoresheet.where(entry_id: entry.id).count
    end
  end
end

app/helpers/scoresheets_helper.rb
module ScoresheetsHelper
end

app/views/scoresheets/_form.html.erb
<%= form_with(model: [@entry, scoresheet], local: true) do |form| %>
  <% if scoresheet.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(scoresheet.errors.count, "error") %> prohibited this scoresheet from being saved:</h2>

      <ul>
        <% scoresheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3><%= @entry.entry_name %></h3>

  <% if current_user.admin? %>
    <strong>Person Judging this Entry</strong>
    <%= form.select :user_id, JudgeAssign.joins(:user).where(entry_id: @entry.id).map{ |m| ["#{m.user.email} - #{m.user.sca_name}", m.user_id] }%>
  <% end %>

  <p>
    <strong>Name:</strong>
    <%= @entry.division.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= simple_format @entry.division.description %>
  </p>

  <% @criteria_types.by_division(@entry.division).in_order.each do |criteria_type| %>
    <p>
      <strong><%= criteria_type.name %></strong>
    </p>

    <p><%= criteria_type.description %></p>

    <% criteria_type.criteriums.order(:suggested_score).each do |criteria| %>
      <p><%= "#{criteria.suggested_score} - #{criteria.description}" %></p>
    <% end %>


<!-- children start here -->

    <% @criteria_types.children_for(criteria_type).applicable(@entry.division).each do |child_criteria| %>
      <strong><%= child_criteria.description %></strong>
      <ul>
        <% Criterium.where(criteria_type_id: child_criteria.id).each do |child_criterium| %>
          <li><%= child_criterium.description %></li>
        <% end %>
      </ul>
      <%= form.fields_for 'scores[]', @scoresheet.scores.select {|n| n.criteria_type_id == child_criteria.id}.first do |score_fields| %>
        <%= render partial: 'sub_criteria_scoresheet', locals: {form: score_fields, criteria: child_criteria} %>
      <% end %>
      <hr>
    <% end %>

<!-- children end here -->

    <b><%= "Score for #{criteria_type.description}" %></b>
    <%= form.fields_for 'scores[]', @scoresheet.scores.select {|n| n.criteria_type_id == criteria_type.id}.first do |score_fields| %>
      <%# if ["Scope", "Skill"].include?(criteria_type.description) %>
        <%#= render partial: 'scoresheet_sub_criteria_total', locals: {form: score_fields, criteria: criteria_type} %>
      <%# else %>
        <%= render partial: 'scoresheet', locals: {form: score_fields, criteria: criteria_type} %>
      <%# end %>
    <% end %>
    <hr>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scoresheets/index.html.erb
<%= render partial: "layouts/filter", path: scoresheets_path %>


<h1>Scoresheets</h1>

<table>
  <thead>
  <tr>
    <th>Entries you are assigned to</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.entry_name %></td>
      <td><%= link_to 'New Scoresheet', new_entry_scoresheet_path(entry) %></td>
      <td><%= "You are assigned as a shadow judge." if JudgeAssign.find_by(entry_id: entry.id).shadow %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>

<table>
  <thead>
  <tr>
    <th>Submitted scoresheets</th>
    <% if current_user.admin? %>
      <th>Judge</th>
    <% end %>
    <th>Faire</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @scoresheets.each do |scoresheet| %>
    <tr>
      <td><%= scoresheet.entry.entry_name %></td>
      <% if current_user.admin? %>
        <td><%= scoresheet.user.email_or_name %></td>
      <% end %>
      <td><%= scoresheet.entry.fair.name %></td>
      <td><%= link_to 'View Details', entry_scoresheet_path(scoresheet.entry, scoresheet) %></td>
      <td><%= link_to 'Edit', edit_entry_scoresheet_path(scoresheet.entry, scoresheet) %></td>
      <% if current_user.admin? %>
        <td><%= link_to 'Delete', [scoresheet.entry, scoresheet], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br><%= link_to 'Back', root_path %>

app/views/scoresheets/show.html.erb
<h3><%= @entry.entry_name %></h3>
<h5><%= @entry.fair.name %></h5>
<% if @scoresheet.shadow_scoresheet? %>
  <h4>This is a shadow judge scoresheet.</h4>
<% end %>
<hr>
<p>
  <strong>Judge:</strong>
  <%= @scoresheet.user.email_or_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @entry.division.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format @entry.division.description %>
</p>

<% CriteriaTypeRepository.by_scoresheet(@scoresheet.id).in_order.each do |criteria_type| %>
  <p>
    <strong><%= criteria_type.name %></strong>
  </p>

  <p><%= criteria_type.description %></p>

  <% criteria_type.criteriums.order(:suggested_score).each do |criteria| %>
    <p><%= "#{criteria.suggested_score} - #{criteria.description}" %></p>
  <% end %>

  <%# CriteriaType.all.children_for(criteria_type).applicable(@entry.division).each do |child_criteria| %>
<!--    <strong><%#= child_criteria.description %></strong>-->
<!--    <ul>-->
      <%# Criterium.where(criteria_type_id: child_criteria.id).each do |child_criterium| %>
<!--        <li><%#= child_criterium.description %></li>-->
      <%# end %>
<!--    </ul>-->
    <%#= render partial: 'sub_criteria_score', locals: {score: @scoresheet.scores.find_by(criteria_type_id: child_criteria.id)} %>
<!--    <hr>-->
  <%# end %>

  <%= render partial: 'score', locals: {score: @scoresheet.scores.find_by(criteria_type_id: criteria_type.id)} %>
  <hr>
<% end %>

<div><b>Total Score:</b>  <%= @scoresheet.total_score %></div>


<% if @current_user == @scoresheet.user %>
  <%= link_to 'Edit', edit_entry_scoresheet_path(@scoresheet.entry, @scoresheet) %> |
  <%= link_to 'Back', scoresheets_path %>
<% else %>
  <%= link_to 'Back', entries_path %>
<% end %>

<br>

<script type="text/javascript">
    function printpage()
    {
        window.print()
    }
</script>

<%= link_to "Print Page", '#', onclick: "printpage()" %>